# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 10:38
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_applicants', models.IntegerField(default=-1, help_text='Total number of applicants')),
                ('male_applicants', models.IntegerField(default=-1, help_text='Total number of male applicants')),
                ('female_applicants', models.IntegerField(default=-1, help_text='Total number of female applicants')),
                ('total_admissions', models.IntegerField(default=-1, help_text='Total number of admissions')),
                ('male_admissions', models.IntegerField(default=-1, help_text='Total number of male admissions')),
                ('female_admissions', models.IntegerField(default=-1, help_text='Total number of female admissions')),
                ('total_enrollment', models.IntegerField(default=-1, help_text='Total enrollment')),
                ('male_enrollment', models.IntegerField(default=-1, help_text='Male enrollment')),
                ('female_enrollment', models.IntegerField(default=-1, help_text='Female enrollment')),
                ('ft_enrollment', models.IntegerField(default=-1, help_text='Total full-time enrollment')),
                ('ft_male_enrollment', models.IntegerField(default=-1, help_text='Total male full-time enrollment')),
                ('ft_female_enrollment', models.IntegerField(default=-1, help_text='Total female full-time enrollment')),
                ('pt_enrollment', models.IntegerField(default=-1, help_text='Total part-time enrollment')),
                ('pt_male_enrollment', models.IntegerField(default=-1, help_text='Total male part-time enrollment')),
                ('pt_female_enrollment', models.IntegerField(default=-1, help_text='Total female part-time enrollment')),
                ('sat_reading_25', models.IntegerField(default=-1, help_text='SAT critical reading 25th percentile')),
                ('sat_reading_75', models.IntegerField(default=-1, help_text='SAT critical reading 75th percentile')),
                ('sat_math_25', models.IntegerField(default=-1, help_text='SAT math 25th percentile')),
                ('sat_math_75', models.IntegerField(default=-1, help_text='SAT math 75th percentile')),
                ('sat_writing_25', models.IntegerField(default=-1, help_text='SAT writing 25th percentile')),
                ('sat_writing_75', models.IntegerField(default=-1, help_text='SAT writing 75th percentile')),
                ('act_composite_25', models.IntegerField(default=-1, help_text='ACT composite 25th percentile')),
                ('act_composite_75', models.IntegerField(default=-1, help_text='ACT composite 75th percentile')),
                ('act_english_25', models.IntegerField(default=-1, help_text='ACT english 25th percentile')),
                ('act_english_75', models.IntegerField(default=-1, help_text='ACT english 75th percentile')),
                ('act_math_25', models.IntegerField(default=-1, help_text='ACT math 25th percentile')),
                ('act_math_75', models.IntegerField(default=-1, help_text='ACT math 75th percentile')),
                ('act_writing_25', models.IntegerField(default=-1, help_text='ACT writing 25th percentile')),
                ('act_writing_75', models.IntegerField(default=-1, help_text='ACT writing 75th percentile')),
            ],
        ),
        migrations.CreateModel(
            name='AliasTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bureau_type', models.IntegerField(choices=[(0, 'Census'), (1, 'Bureau of Labor'), (2, 'Office of Management'), (3, 'Education')], default=3)),
                ('alias_title', models.CharField(db_index=True, default='', help_text='Alias CIP occupation title', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_level', models.IntegerField(default=-1, help_text='Institution award level')),
                ('total_awards', models.IntegerField(default=-1, help_text='Total awards for this program')),
                ('total_awards_male', models.IntegerField(default=-1, help_text='Total awards of this program to men')),
                ('total_awards_female', models.IntegerField(default=-1, help_text='Total awards of this program to women')),
            ],
        ),
        migrations.CreateModel(
            name='Crosswalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('census_code', models.IntegerField(default=-1, help_text='Census 2000 occupation code')),
                ('census_occupation_title', models.CharField(db_index=True, default='No Title', help_text='Census Occupation Title', max_length=200)),
                ('bls_code', models.CharField(db_index=True, default='No Code', help_text='Bureau of Labor Code', max_length=100)),
                ('bls_occupation_title', models.CharField(db_index=True, default='No Title', help_text='Bureau of Labor occupation title', max_length=200)),
                ('ombsoc_code', models.CharField(db_index=True, default='No Code', help_text='OMB Standard Occupation Classification code', max_length=100)),
                ('ombsoc_occupation_title', models.CharField(db_index=True, default='No Title', help_text='OMB Standard Occupation Classification title', max_length=200)),
                ('cip_code', models.CharField(db_index=True, default='No Code', help_text='CIP code', max_length=100)),
                ('cip_occupation_title', models.CharField(db_index=True, default='No Title', help_text='CIP occupation', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitid', models.IntegerField(help_text='Institution unit ID', unique=True)),
                ('name', models.CharField(db_index=True, default='', help_text='Institution name', max_length=100)),
                ('address', models.CharField(default='', help_text='Address of institution', max_length=100)),
                ('city', models.CharField(default='', help_text='City of institution', max_length=50)),
                ('state', models.CharField(default='', help_text='State', max_length=3)),
                ('ein', models.CharField(default='', help_text='IRS EIN number', max_length=20)),
                ('location_region', models.IntegerField(choices=[(0, 'US Service School'), (1, 'New England (CT, ME, MA, NH, RI, VT)'), (2, 'Mid East (DC, DE, MD, NH, NY, PA)'), (3, 'Great Lakes (IL, IN, MI, OH, WI'), (4, 'Plains (IA, KS, MN, MO, NE, ND, SD)'), (5, 'Southeast (AL, AR, FL, GA, KY, LA, MS, NC, SC, TN, VA, WV)'), (6, 'Southwest (AX NM, OK, TX)'), (7, 'Rocky Mountains (CO, ID, MT, UT, WY)'), (8, 'Far West (AK, CA, HI, NV, OR, WA)'), (9, 'Outlying Areas (AS, FM, GU, MH, MP, PR, PW, VI)'), (-3, 'Not Available')], default=-3, help_text='Bureau of Economic Analysis Region')),
                ('web_address', models.URLField(default='', help_text='Institution web address', max_length=255)),
                ('admission_url', models.URLField(default='', help_text='Admission URL', max_length=255)),
                ('financial_aid_url', models.URLField(default='', help_text='Financial Aid URL', max_length=255)),
                ('application_url', models.URLField(default='', help_text='Application URL', max_length=255)),
                ('net_price_url', models.URLField(default='', help_text='Net Price Calculator URL', max_length=255)),
                ('sector', models.IntegerField(choices=[(0, 'Administrative Unit'), (1, 'Public, 4 Year or Above'), (2, 'Private Non Profit, 4 Year or Above'), (3, 'Private For Profit, 4 Year or Above'), (4, 'Public, 2 Year'), (5, 'Private Non Profit, 2 Year'), (6, 'Private For Profit, 2 Year'), (7, 'Public, Less Than 2 Year'), (8, 'Private Non Profit, Less Than 2 Year'), (9, 'Private For Profit, Less Than 2 Year'), (99, 'Sector Unknown')], default=99, help_text='Institution category joining level and control')),
                ('level', models.IntegerField(choices=[(1, 'Four or more years'), (2, 'At least 2 years and less than 4'), (3, 'Less than 2 years (Below Associate)'), (-3, 'Not Available')], default=-3, help_text='Classification of institution programs by year length')),
                ('control', models.IntegerField(choices=[(1, 'Public'), (2, 'Private Non Profit'), (3, 'Private For Profit'), (-3, 'Not Available')], default=-3, help_text='Institution operated publicly or private')),
                ('highest_award', models.IntegerField(choices=[(0, 'Other'), (1, 'Postsecondary award, certificate or diploma of less than one academic year'), (2, 'Postsecondary award, certificate or diploma of at least one but less than two academic years'), (3, "Associate's degree"), (4, 'Postsecondary award, certificate or diploma of at least two but less than four academic years'), (5, "Bachelor's degree"), (6, 'Postbaccalaureate certificate'), (7, "Master's degree"), (8, "Post-Master's degree"), (9, "Doctor's degree"), (-3, 'Not Available')], default=-3, help_text='Highest offering award')),
                ('locale', models.IntegerField(choices=[(11, 'Large city with population > 250,000'), (12, 'Mid-sized city with population between 100,000 and 250,000'), (13, 'Small city with population < 100,000'), (21, 'Large suburb with population > 250,000'), (22, 'Mid-sized surburb with population between 100,000 and 250,000'), (23, 'Small suburb with population less than 100,000'), (31, 'Fringe town <= 10 miles from nearest urbanized area'), (32, 'Distant town between 10 and 35 miles from nearest urbanized area'), (33, 'Remote town that is > 35 miles from nearest urbanized area'), (41, 'Rural, Fringe'), (42, 'Rural, Distant'), (43, 'Rural, Remote'), (-3, 'Not Available')], default=-3, help_text='Geographic status of a school based on surrounding population and distance')),
                ('enrollment', models.IntegerField(default=-1, help_text='Total student enrollment')),
                ('system_type', models.IntegerField(choices=[(1, 'Multi-institution or multi-campus'), (2, 'Not multi-institution or multi-campus'), (-1, 'Not Reported'), (-2, 'Not Applicable')], default=-2, help_text='Multi-institution or multi-campus organization')),
                ('system_name', models.CharField(default='', help_text='Name of multi-instition or multi-campus organization', max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year_2013_books', models.IntegerField(default=-1, help_text='2013 academic year books and supplies')),
                ('academic_year_2014_books', models.IntegerField(default=-1, help_text='2014 academic year books and supplies')),
                ('academic_year_2015_books', models.IntegerField(default=-1, help_text='2015 academic year books and supplies')),
                ('academic_year_2013_board', models.IntegerField(default=-1, help_text='2013 academic year on-campus room and board')),
                ('academic_year_2014_board', models.IntegerField(default=-1, help_text='2014 academic year on-campus room and board')),
                ('academic_year_2015_board', models.IntegerField(default=-1, help_text='2015 academic year on-campus room and board')),
                ('tuition_class', models.IntegerField(choices=[(0, 'In District'), (1, 'In State'), (2, 'Out of State'), (-1, 'Not Applicable')], default=-1, help_text='Tuition rates of student origin')),
                ('cost', models.IntegerField(default=-1, help_text='List price for annual tuition')),
                ('fees', models.IntegerField(default=-1, help_text='List price for annual fees - full time enrollment')),
                ('credit_hour', models.IntegerField(default=-1, help_text='List price of credit hour cost')),
                ('academic_year_2013_cost', models.IntegerField(default=-1, help_text='2013 academic year cost and fees')),
                ('academic_year_2014_cost', models.IntegerField(default=-1, help_text='2014 academic year cost and fees')),
                ('academic_year_2015_cost', models.IntegerField(default=-1, help_text='2015 academic year cost and fees')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuitions', related_query_name='tuition', to='app.Institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='completion',
            name='cip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cips', related_query_name='cip', to='app.Crosswalk'),
        ),
        migrations.AddField(
            model_name='completion',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', related_query_name='completion', to='app.Institution'),
        ),
        migrations.AddField(
            model_name='aliastitle',
            name='cip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', related_query_name='alias', to='app.Crosswalk'),
        ),
        migrations.AddField(
            model_name='admission',
            name='institution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Institution'),
        ),
    ]
