# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='ein',
            field=models.CharField(default='', help_text='IRS EIN number', max_length=20),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='tuition_class',
            field=models.IntegerField(choices=[(0, 'In District'), (1, 'In State'), (2, 'Out of State'), (-1, 'Not Applicable')], default=-1, help_text='Tuition rates of student origin'),
        ),
    ]
