# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170506_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuition',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuitions', related_query_name='tuition', to='app.Institution'),
        ),
    ]
