# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cip_completions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cip',
            name='bls_occupation_title',
            field=models.CharField(db_index=True, default='', help_text='Bureau of Labor occupation title', max_length=200),
        ),
        migrations.AlterField(
            model_name='cip',
            name='census_occupation_title',
            field=models.CharField(db_index=True, default='', help_text='Census Occupation Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='cip',
            name='cip_occupation_title',
            field=models.CharField(db_index=True, default='', help_text='CIP occupation', max_length=200),
        ),
        migrations.AlterField(
            model_name='cip',
            name='ombsoc_occupation_title',
            field=models.CharField(db_index=True, default='', help_text='OMB Standard Occupation Classification title', max_length=200),
        ),
    ]
