# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170507_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bureau_type', models.IntegerField(choices=[(0, 'Census'), (1, 'Bureau of Labor'), (2, 'Office of Management'), (3, 'Education')], default=3)),
                ('alias_title', models.CharField(db_index=True, default='', help_text='Alias CIP occupation title', max_length=200)),
                ('cip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', related_query_name='alias', to='app.CIP')),
            ],
        ),
    ]
