# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_aliastitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completions',
            name='cip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cips', related_query_name='cip', to='app.CIP'),
        ),
    ]
