# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aliastitle',
            old_name='cip',
            new_name='crosswalk',
        ),
        migrations.RenameField(
            model_name='completion',
            old_name='cip',
            new_name='crosswalk',
        ),
    ]
